window_width = 'WINDOWWIDTH'
window_height = 'WINDOWHEIGHT'
board_width  = 'BOARDWIDTH'
board_height = 'BOARDHEIGHT'
text_color = 'TEXTCOLOR'
text_bg_color_1 = 'TEXTBGCOLOR1'
text_bg_color_2 = 'TEXTBGCOLOR2'